// <auto-generated />
using System;
using DataService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712044914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DataService.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DataService.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Age = 20,
                            Dob = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "John Doe",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            Age = 21,
                            Dob = new DateTime(2005, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Jane Smith",
                            Phone = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd",
                            Age = 22,
                            Dob = new DateTime(2004, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bob Johnson",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Elm St",
                            Age = 19,
                            Dob = new DateTime(2007, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Alice Williams",
                            Phone = "444-555-6666"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Spruce Ln",
                            Age = 23,
                            Dob = new DateTime(2003, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Charlie Brown",
                            Phone = "333-444-5555"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
